[project]
name = "workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vijaykeshav111-beg2adv", email = "vijaykeshav111" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
]

[project.scripts]
workshop = "workshop:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
